# Generated by Django 3.2.7 on 2021-09-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='capa',
            field=models.FileField(upload_to='imagens'),
        ),
    ]
